name: Build Docker image

workflow_dispatch:

jobs:
  create_acr_prod_tags:
    outputs:
      acr_tags: ${{ steps.set_tags.outputs.ACR_TAGS }}

    steps:
    - name: set tags
      id: set_tags
      run: |
        REPO="octaipipepublic.azurecr.io/octaipipe_kf_patcher"
        GH_SHA=$(git rev-parse --short HEAD)
        echo "ACR_TAGS=${REPO}:latest,${REPO}:${GH_SHA}" >> $GITHUB_OUTPUT

  build_and_push_prod_image:
    runs-on: ubuntu-20.04
    needs: create_acr_prod_tags
    steps:
    - uses: actions/checkout@v4

    - name: Login to azure
      uses: azure/login@v2
      with:
        creds: '{
                  "clientId": "${{ vars.AZURE_CLIENT_ID }}",
                  "tenantId": "${{ vars.AZURE_TENANT_ID }}",
                  "subscriptionId": "${{ vars.AZURE_SUBSCRIPTION_ID }}",
                  "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}"
                  }'

    - name: log in to registry
      run: az acr login -n octaipipepublic

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push the image
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: linux/amd64
        file: ./Dockerfile
        tags: ${{ needs.create_acr_prod_tags.outputs.acr_tags }}
        push: true
